# Generated by Django 2.2.19 on 2021-03-22 09:47

import django.db.models.deletion
import topmic
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mrating",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mrating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="films.Movie"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director",
                to="films.Person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(to="films.Genre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="screenplay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screenplay",
                to="films.Person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="starring",
            field=models.ManyToManyField(
                through="films.PersonMovie", to="films.Person"
            ),
        ),
    ]
