# Generated by Django 2.2.19 on 2021-03-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='films.Job'),
        ),
    ]
