# Generated by Django 2.2.19 on 2021-03-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_person_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
