# Generated by Django 2.2.19 on 2021-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20210310_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(null=True, upload_to='static/films/movie_images'),
        ),
    ]
