# Generated by Django 2.2.19 on 2021-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20210310_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.FileField(null=True, upload_to='covers'),
        ),
    ]
